#ifndef PSM_SRC_UNDO_MY_LIBC_PROHIBIT_LIBC_H
#define PSM_SRC_UNDO_MY_LIBC_PROHIBIT_LIBC_H

// Prohibits libc wrappers for syscalls.

#define read DO_NOT_USE
#define write DO_NOT_USE
#define open DO_NOT_USE
#define close DO_NOT_USE
// #define stat DO_NOT_USE
#define fstat DO_NOT_USE
#define lstat DO_NOT_USE
#define poll DO_NOT_USE
#define lseek DO_NOT_USE
#define mmap DO_NOT_USE
#define mprotect DO_NOT_USE
#define munmap DO_NOT_USE
#define brk DO_NOT_USE
#define rt_sigaction DO_NOT_USE
#define rt_sigprocmask DO_NOT_USE
#define rt_sigreturn DO_NOT_USE
#define ioctl DO_NOT_USE
#define pread64 DO_NOT_USE
#define pwrite64 DO_NOT_USE
#define readv DO_NOT_USE
#define writev DO_NOT_USE
#define access DO_NOT_USE
#define pipe DO_NOT_USE
#define select DO_NOT_USE
#define sched_yield DO_NOT_USE
#define mremap DO_NOT_USE
#define msync DO_NOT_USE
#define mincore DO_NOT_USE
#define madvise DO_NOT_USE
#define shmget DO_NOT_USE
#define shmat DO_NOT_USE
#define shmctl DO_NOT_USE
#define dup DO_NOT_USE
#define dup2 DO_NOT_USE
#define pause DO_NOT_USE
#define nanosleep DO_NOT_USE
#define getitimer DO_NOT_USE
#define alarm DO_NOT_USE
#define setitimer DO_NOT_USE
#define getpid DO_NOT_USE
#define sendfile DO_NOT_USE
#define socket DO_NOT_USE
#define connect DO_NOT_USE
#define accept DO_NOT_USE
#define sendto DO_NOT_USE
#define recvfrom DO_NOT_USE
#define sendmsg DO_NOT_USE
#define recvmsg DO_NOT_USE
#define shutdown DO_NOT_USE
#define bind DO_NOT_USE
#define listen DO_NOT_USE
#define getsockname DO_NOT_USE
#define getpeername DO_NOT_USE
#define socketpair DO_NOT_USE
#define setsockopt DO_NOT_USE
#define getsockopt DO_NOT_USE
#define clone DO_NOT_USE
#define fork DO_NOT_USE
#define vfork DO_NOT_USE
#define execve DO_NOT_USE
#define exit DO_NOT_USE
#define wait4 DO_NOT_USE
#define kill DO_NOT_USE
#define uname DO_NOT_USE
#define semget DO_NOT_USE
#define semop DO_NOT_USE
#define semctl DO_NOT_USE
#define shmdt DO_NOT_USE
#define msgget DO_NOT_USE
#define msgsnd DO_NOT_USE
#define msgrcv DO_NOT_USE
#define msgctl DO_NOT_USE
#define fcntl DO_NOT_USE
#define flock DO_NOT_USE
#define fsync DO_NOT_USE
#define fdatasync DO_NOT_USE
#define truncate DO_NOT_USE
#define ftruncate DO_NOT_USE
#define getdents DO_NOT_USE
#define getcwd DO_NOT_USE
#define chdir DO_NOT_USE
#define fchdir DO_NOT_USE
#define rename DO_NOT_USE
#define mkdir DO_NOT_USE
#define rmdir DO_NOT_USE
#define creat DO_NOT_USE
#define link DO_NOT_USE
#define unlink DO_NOT_USE
#define symlink DO_NOT_USE
#define readlink DO_NOT_USE
#define chmod DO_NOT_USE
#define fchmod DO_NOT_USE
#define chown DO_NOT_USE
#define fchown DO_NOT_USE
#define lchown DO_NOT_USE
#define umask DO_NOT_USE
#define gettimeofday DO_NOT_USE
#define getrlimit DO_NOT_USE
#define getrusage DO_NOT_USE
#define sysinfo DO_NOT_USE
#define times DO_NOT_USE
#define ptrace DO_NOT_USE
#define getuid DO_NOT_USE
#define syslog DO_NOT_USE
#define getgid DO_NOT_USE
#define setuid DO_NOT_USE
#define setgid DO_NOT_USE
#define geteuid DO_NOT_USE
#define getegid DO_NOT_USE
#define setpgid DO_NOT_USE
#define getppid DO_NOT_USE
#define getpgrp DO_NOT_USE
#define setsid DO_NOT_USE
#define setreuid DO_NOT_USE
#define setregid DO_NOT_USE
#define getgroups DO_NOT_USE
#define setgroups DO_NOT_USE
#define setresuid DO_NOT_USE
#define getresuid DO_NOT_USE
#define setresgid DO_NOT_USE
#define getresgid DO_NOT_USE
#define getpgid DO_NOT_USE
#define setfsuid DO_NOT_USE
#define setfsgid DO_NOT_USE
#define getsid DO_NOT_USE
#define capget DO_NOT_USE
#define capset DO_NOT_USE
#define rt_sigpending DO_NOT_USE
#define rt_sigtimedwait DO_NOT_USE
#define rt_sigqueueinfo DO_NOT_USE
#define rt_sigsuspend DO_NOT_USE
#define sigaltstack DO_NOT_USE
#define utime DO_NOT_USE
#define mknod DO_NOT_USE
#define uselib DO_NOT_USE
#define personality DO_NOT_USE
#define ustat DO_NOT_USE
#define statfs DO_NOT_USE
#define fstatfs DO_NOT_USE
#define sysfs DO_NOT_USE
#define getpriority DO_NOT_USE
#define setpriority DO_NOT_USE
#define sched_setparam DO_NOT_USE
#define sched_getparam DO_NOT_USE
#define sched_setscheduler DO_NOT_USE
#define sched_getscheduler DO_NOT_USE
#define sched_get_priority_max DO_NOT_USE
#define sched_get_priority_min DO_NOT_USE
#define sched_rr_get_interval DO_NOT_USE
#define mlock DO_NOT_USE
#define munlock DO_NOT_USE
#define mlockall DO_NOT_USE
#define munlockall DO_NOT_USE
#define vhangup DO_NOT_USE
#define modify_ldt DO_NOT_USE
#define pivot_root DO_NOT_USE
#define _sysctl DO_NOT_USE
#define prctl DO_NOT_USE
#define arch_prctl DO_NOT_USE
#define adjtimex DO_NOT_USE
#define setrlimit DO_NOT_USE
#define chroot DO_NOT_USE
#define sync DO_NOT_USE
#define acct DO_NOT_USE
#define settimeofday DO_NOT_USE
#define mount DO_NOT_USE
#define umount2 DO_NOT_USE
#define swapon DO_NOT_USE
#define swapoff DO_NOT_USE
#define reboot DO_NOT_USE
#define sethostname DO_NOT_USE
#define setdomainname DO_NOT_USE
#define iopl DO_NOT_USE
#define ioperm DO_NOT_USE
#define create_module DO_NOT_USE
#define init_module DO_NOT_USE
#define delete_module DO_NOT_USE
#define get_kernel_syms DO_NOT_USE
#define query_module DO_NOT_USE
#define quotactl DO_NOT_USE
#define nfsservctl DO_NOT_USE
#define getpmsg DO_NOT_USE
#define putpmsg DO_NOT_USE
#define afs_syscall DO_NOT_USE
#define tuxcall DO_NOT_USE
#define security DO_NOT_USE
#define gettid DO_NOT_USE
#define readahead DO_NOT_USE
#define setxattr DO_NOT_USE
#define lsetxattr DO_NOT_USE
#define fsetxattr DO_NOT_USE
#define getxattr DO_NOT_USE
#define lgetxattr DO_NOT_USE
#define fgetxattr DO_NOT_USE
#define listxattr DO_NOT_USE
#define llistxattr DO_NOT_USE
#define flistxattr DO_NOT_USE
#define removexattr DO_NOT_USE
#define lremovexattr DO_NOT_USE
#define fremovexattr DO_NOT_USE
#define tkill DO_NOT_USE
#define time DO_NOT_USE
#define futex DO_NOT_USE
#define sched_setaffinity DO_NOT_USE
#define sched_getaffinity DO_NOT_USE
#define set_thread_area DO_NOT_USE
#define io_setup DO_NOT_USE
#define io_destroy DO_NOT_USE
#define io_getevents DO_NOT_USE
#define io_submit DO_NOT_USE
#define io_cancel DO_NOT_USE
#define get_thread_area DO_NOT_USE
#define lookup_dcookie DO_NOT_USE
#define epoll_create DO_NOT_USE
#define epoll_ctl_old DO_NOT_USE
#define epoll_wait_old DO_NOT_USE
#define remap_file_pages DO_NOT_USE
#define getdents64 DO_NOT_USE
#define set_tid_address DO_NOT_USE
#define restart_syscall DO_NOT_USE
#define semtimedop DO_NOT_USE
#define fadvise64 DO_NOT_USE
#define timer_create DO_NOT_USE
#define timer_settime DO_NOT_USE
#define timer_gettime DO_NOT_USE
#define timer_getoverrun DO_NOT_USE
#define timer_delete DO_NOT_USE
#define clock_settime DO_NOT_USE
#define clock_gettime DO_NOT_USE
#define clock_getres DO_NOT_USE
#define clock_nanosleep DO_NOT_USE
#define exit_group DO_NOT_USE
#define epoll_wait DO_NOT_USE
#define epoll_ctl DO_NOT_USE
#define tgkill DO_NOT_USE
#define utimes DO_NOT_USE
#define vserver DO_NOT_USE
#define mbind DO_NOT_USE
#define set_mempolicy DO_NOT_USE
#define get_mempolicy DO_NOT_USE
#define mq_open DO_NOT_USE
#define mq_unlink DO_NOT_USE
#define mq_timedsend DO_NOT_USE
#define mq_timedreceive DO_NOT_USE
#define mq_notify DO_NOT_USE
#define mq_getsetattr DO_NOT_USE
#define kexec_load DO_NOT_USE
#define waitid DO_NOT_USE
#define add_key DO_NOT_USE
#define request_key DO_NOT_USE
#define keyctl DO_NOT_USE
#define ioprio_set DO_NOT_USE
#define ioprio_get DO_NOT_USE
#define inotify_init DO_NOT_USE
#define inotify_add_watch DO_NOT_USE
#define inotify_rm_watch DO_NOT_USE
#define migrate_pages DO_NOT_USE
#define openat DO_NOT_USE
#define mkdirat DO_NOT_USE
#define mknodat DO_NOT_USE
#define fchownat DO_NOT_USE
#define futimesat DO_NOT_USE
#define newfstatat DO_NOT_USE
#define unlinkat DO_NOT_USE
#define renameat DO_NOT_USE
#define linkat DO_NOT_USE
#define symlinkat DO_NOT_USE
#define readlinkat DO_NOT_USE
#define fchmodat DO_NOT_USE
#define faccessat DO_NOT_USE
#define pselect6 DO_NOT_USE
#define ppoll DO_NOT_USE
#define unshare DO_NOT_USE
#define set_robust_list DO_NOT_USE
#define get_robust_list DO_NOT_USE
#define splice DO_NOT_USE
#define tee DO_NOT_USE
#define sync_file_range DO_NOT_USE
#define vmsplice DO_NOT_USE
#define move_pages DO_NOT_USE
#define utimensat DO_NOT_USE
#define epoll_pwait DO_NOT_USE
#define signalfd DO_NOT_USE
#define timerfd_create DO_NOT_USE
#define eventfd DO_NOT_USE
#define fallocate DO_NOT_USE
#define timerfd_settime DO_NOT_USE
#define timerfd_gettime DO_NOT_USE
#define accept4 DO_NOT_USE
#define signalfd4 DO_NOT_USE
#define eventfd2 DO_NOT_USE
#define epoll_create1 DO_NOT_USE
#define dup3 DO_NOT_USE
#define pipe2 DO_NOT_USE
#define inotify_init1 DO_NOT_USE
#define preadv DO_NOT_USE
#define pwritev DO_NOT_USE
#define rt_tgsigqueueinfo DO_NOT_USE
#define perf_event_open DO_NOT_USE
#define recvmmsg DO_NOT_USE
#define fanotify_init DO_NOT_USE
#define fanotify_mark DO_NOT_USE
#define prlimit64 DO_NOT_USE
#define name_to_handle_at DO_NOT_USE
#define open_by_handle_at DO_NOT_USE
#define clock_adjtime DO_NOT_USE
#define syncfs DO_NOT_USE
#define sendmmsg DO_NOT_USE
#define setns DO_NOT_USE
#define getcpu DO_NOT_USE
#define process_vm_readv DO_NOT_USE
#define process_vm_writev DO_NOT_USE
#define kcmp DO_NOT_USE
#define finit_module DO_NOT_USE

#endif //PSM_SRC_UNDO_MY_LIBC_PROHIBIT_LIBC_H
